import './App.css';

function App() {
return (
<div className="typewriter">
<h1 className="heading"> WELCOME,HUMAN.. EMBRACE
THE POSSIBILITIES THAT LIE AHEAD, FOR HERE, 
THE CONVERGENCE OF HUMAN INGENUITY AND ARTIFICIAL INTELLIGENCE {'/n'} SPARKS A NEW ERA OF DISCOVERY.
PREPARE TO UNLOCK THE DOORS OF {'/n'} PERCEPTION AND EMBARK UPON A JOURNEY THAT
TRANSCENDS THE LIMITS OF
THE TANGIBLE WORLD.</h1>
</div>
);
}

export default App;
